apiVersion: apps/v1
kind: Deployment
metadata:
  name: disaster-frontend
  namespace: disasterconnect
  labels:
    app: disaster-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disaster-frontend
  template:
    metadata:
      labels:
        app: disaster-frontend
    spec:
      containers:
        - name: frontend
          image: gmisk/disaster-frontend:latest # <-- use your image here
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: disaster-frontend
  namespace: disasterconnect
  labels:
    app: disaster-frontend
spec:
  type: NodePort  
  selector:
    app: disaster-frontend
  ports:
    - port: 80        
      targetPort: 80  # containerPort
      nodePort: 30080